[package]
name = "array_math"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Math operations on arrays"
repository = "https://github.com/sigurd4/array_math"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moddef = "0.2.2"
array_trait = "0.6.14"
float_approx_math = "0.1.2"